# Generated by Django 3.2.4 on 2022-09-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=50)),
                ('expire', models.BooleanField()),
                ('expiration_date', models.DateTimeField(null=True)),
                ('alerting_device', models.CharField(choices=[('e-mail', 'e-mail'), ('sms', 'sms'), ('notification', 'notification')], default='notification', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('protection_level', models.CharField(choices=[('private', 'private'), ('limited', 'limited'), ('public', 'public')], default='private', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('alert_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPairOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('ask', 'ask'), ('bid', 'bid')], default='ask', max_length=3)),
                ('liquidity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('closeout_ask', models.FloatField(default=0.0)),
                ('closeout_bid', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.currencypair')),
            ],
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('ask', 'ask'), ('bid', 'bid')], max_length=50)),
                ('trigger_condition', models.CharField(choices=[('crossing', 'crossing'), ('upcrossing', 'upcrossing'), ('downcrossing', 'downcrossing'), ('bigger than', 'bigger than'), ('lesser than', 'lesser than'), ('percentage increase', 'percentage increase'), ('percentage decrease', 'percentage decrease')], max_length=50)),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.alert')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.currencypair'),
        ),
    ]
