# Generated by Django 3.2.4 on 2022-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttrigger',
            name='trigger_condition',
            field=models.CharField(choices=[('crossing', 'crossing'), ('upcrossing', 'upcrossing'), ('downcrossing', 'downcrossing'), ('bigger than', 'bigger than'), ('lesser than', 'lesser than'), ('percentage increase', 'percentage increase'), ('percentage decrease', 'percentage decrease'), ('pip increase', 'pip increase'), ('pip decrease', 'pip decrease')], max_length=50),
        ),
    ]
