# Generated by Django 3.2.4 on 2021-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='random_uuid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
