# Generated by Django 3.2.4 on 2021-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_random_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='random_uuid',
            new_name='random_uuid_password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='random_uuid_register',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
