# Generated by Django 3.2.4 on 2021-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20211104_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.CharField(choices=[(1, 'beginner'), (2, 'intermediate'), (3, 'advanced')], default=1, max_length=12),
        ),
    ]
