# Generated by Django 3.2.4 on 2021-12-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_customuser_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default=1, max_length=12),
        ),
    ]
