# Generated by Django 3.2.4 on 2022-01-19 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_customuser_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret',
            field=models.CharField(default=uuid.UUID('06f5bb1f-65ad-4404-bc8e-52fb5da46eb8'), max_length=36),
        ),
    ]
