# Generated by Django 3.2.4 on 2022-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_customuser_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=12),
        ),
    ]
