# Generated by Django 3.2.4 on 2022-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_customuser_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pseudo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
