# Generated by Django 3.2.4 on 2022-01-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_customuser_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visibility',
            field=models.CharField(choices=[('private', 'private'), ('protected', 'protected'), ('public', 'public')], default='private', max_length=11),
        ),
        migrations.CreateModel(
            name='FollowingRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
